### ISSUE TITLE
just use `unit4s` top level package?

### ISSUE THREAD

**Issue by erikerlandson** [erikerlandson/unit4s#5]

**Comment by Daenyth** [comment]
I'd like this

**Comment by erikerlandson** [comment]
I've been speaking with a colleague who has been recommending that I stay with a more qualified package name, on the grounds that it is better scoping practice, and that is tends to be more compliant with organization naming conventions.

My latest plan is to name the "official" library `coulomb`, with qualified package `com.manyangled.coulomb`, and move development over to a corresponding GH project:
https://github.com/erikerlandson/coulomb

**Comment by erikerlandson** [comment]
https://github.com/erikerlandson/coulomb
